package it.albertus.router.gui.preference;

public enum FieldEditorType {
	Boolean,
	DefaultBoolean,
	String,
	WrapString,
	FormattedString,
	Password,
	Integer,
	File,
	FormattedFile,
	FormattedInteger,
	Scale,
	ScaleInteger,
	Combo,
	FormattedCombo,
	EditableCombo,
	DatabaseCombo,
	DelimiterCombo,
	IntegerCombo,
	ReaderCombo,
	ValidatedCombo,
	WriterCombo,
	Radio,
	DefaultRadio,
	Directory,
	FormattedDirectory,
	EmailAddresses,
	Uri,
	Thresholds;
}
